Changed FKSelector to use likePattern filter
quinscape/automaton-js pull request #189
Opened 2024-12-03 16:25 UTC by ZidArgs-Work

instead of containsIgnoreCase.

Also changed the FKSelector filter renderer to use likePattern renderer to include validation preventing invalid filter values to be executed (like "*")

LISAWEB-2483

2024-12-04 06:54 UTC, mdowideit requested changes

2024-12-04 06:54 UTC, mdowideit commented on src/ui/FKSelector.js
> +        // {
Kann das dann nicht weg?

2024-12-04 06:54 UTC, mdowideit commented on src/ui/FKSelector.js
> +        // }
Das kann auch weg

2024-12-04 09:50 UTC, ZidArgs-Work commented on src/ui/FKSelector.js
> +        // {
zumindest den part `const scalarType = unwrapNonNull(lookupType(type, "rows." + searchFilter)).name;` habe ich mir dann mal weg kopiert falls wir den da doch mal brauchen (z.B. um Datumswerte entsprechend filtern zu können)

2024-12-04 09:50 UTC, ZidArgs-Work commented on src/ui/FKSelector.js
> +        // }
done

2024-12-12 09:42 UTC, mdowideit approved these changes

2024-12-12 09:43 UTC, merged