Add writable check to object property assignment
quinscape/automaton-js pull request #60
Opened 2022-06-23 12:51 UTC by CodedStingray

Add domainql writable check to
object property assignment in clone utility.

2022-06-23 12:53 UTC, CodedStingray commented
requires DomainQL PR 16

2022-06-24 07:07 UTC, mdowideit approved these changes

2022-06-24 07:08 UTC, mdowideit requested changes

2022-06-24 07:08 UTC, mdowideit commented on src/util/clone.js
> +import { isPropertyWritable } from "../../../domainql-form/src/util/PropertyUtils"
Ist der Import so korrekt?

2022-06-30 10:02 UTC, mdowideit approved these changes

2022-06-30 12:01 UTC, merged