Fix initialization of WebSocket
quinscape/automaton-js pull request #80
Opened 2022-08-09 11:40 UTC by ZidArgs

Fix the url for the WebSocket client.

2022-08-09 11:40 UTC, ZidArgs commented
AUTO-126

2022-08-10 09:00 UTC, mdowideit requested changes

2022-08-10 09:00 UTC, mdowideit commented on src/message/Hub.js
> +    const origin = location.origin.replace(/^http/, "ws");
Was ist wenn das auf https läuft?

2022-08-10 10:16 UTC, ZidArgs commented on src/message/Hub.js
> +    const origin = location.origin.replace(/^http/, "ws");
dann wird das korrekterweise wss, was als einziges zulässig ist, wenn man von https kommt

2022-08-10 10:23 UTC, mdowideit approved these changes

2022-08-10 10:24 UTC, merged